sudo: false
language: java
cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/.m2"
jdk:
- openjdk8
before_install:
- export TZ=Asia/Tokyo
before_script:
- date
before_deploy:
- openssl aes-256-cbc -K $encrypted_c0fddd6d7622_key -iv $encrypted_c0fddd6d7622_iv -in .travis.key.gpg.enc -out .travis.key.gpg -d
- chmod 600 .travis.key.gpg
- gpg --import .travis.key.gpg
deploy:
  provider: script
  skip_cleanup: true
  script: mvn -DperformRelease=true --settings .travis.settings.xml
  on:
    tags: true
after_success:
- mvn clean test jacoco:report coveralls:report
- "[[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} == '' ]] && mvn deploy -DskipTests --settings .travis.settings.xml"
notifications:
  email:
    recipients:
    - gr-tig-oss@future.co.jp
    on_success: change
    on_failure: always
env:
  global:
  - secure: VKnQHGR2DXqRQtO/r3S53AevlLrdXLPhBgRrq0/JlS6Nz3tc+mO6k/f6oMNp/quR+kush+aVgQJ0l1aOKvYkeURZxUeK3HkyVPLF69NB/90VtCqZPM4oHyNRSsXHa9u0ak0BA3ZIR0Cjq9vavtCh42IAkpCRtUjHNZ4d08T/n+TjtDJjrAdDU6XxAyIyfu5J41XtIa0DIxd6WFW67ieUrodkQRYADe0A3tTBAWwVYKdvqlqjrIWdQu5ZucWuDaA+pA14LstrmIa3ZYkUvdu/6Q7mdiuMlV6k2g9fxSbnAPzK36mLR7SvzJXbTDUHYe1ZXkOs+REQupHWUHbLHvJFk8CCZQnvzNvK3p2G945uWz1d5BWs9ral7Xj2Qkgz80V0Gws46eHUWwBNYfDGaTvBpUnEUMlAiM1Pl1kZ3IzZy8gTZsORqA0FAMh4yZ85AD7LBMlIfo5m7eWudexr1BUFEQzIPrXZnTLd4Po4ZQN/LUhOioVoJst2G6BsgyqGd485Gaa+ykUP478YqZVjxp5+fsqJQhaDmlXrjul6WMCXWaUb4q+66bgYKoyBfytOvAyIyXSdSKqOLxPMfAGJhdvXy82dvSbktI5YnCkgjRXNKGfs0KGX2ghdWX1IXqiQB98RZ0zFO8P/3Xagu9amXPavb2wQQPmWPF8/rbWO1x/p6FY=
  - secure: fx6fY0ncs8Qw3xdNz9j8TqNfpXVZCsGutJ7k2RzTVaqFXqyqme3yQRm0l0OZb+TAkMdvvX3FFaqfMmSRTnVdolZiYyzjoY59fE1rGnuWLUfzxLWv3NAVCgnVn8D6JsC3aQ4ENNKjUmW7UNwBJWDTA7SQpLyPNh9HlK+lK5ABIdQ361JQmYyOq14arqo9QJ+MXuPczF9U/X1OgJzP5ChtqY+yu5bRPXCz5yD32vysUXwk8zZwYLFVJJTPTVvXzVlGDd8Wlrr1mIaCdTSq7+1/9V+tLIpNTmMOJUaZBjdY2pnfyl/MdZNVDlb3dlyY6s6M8dY2u9GF6nqf6iHGDLYN5x5i9A0C7Pjr8abMe7FIhCquF2GyhTKtjvhLnymybE/AWsulYU0Vgt1IwcAn/CtOOBhK88qWzC6Ud0Be0UM+AaZ/FY/oOA9Pus/duaqiufB1AqhDQLoUFc18OtOfezlHbxzCKAetdgXd0mzBmzZ7Rdx3d0s8FuKKg5Vhd6jDtA6tSfXszaJGURmIdZ8DwoiZynuJwjf2uvLDayjT38k6hPJ9hTdiXXoMaZ4oSf7UKsxQH2rR/rFaa/8Ww6tCZyzbCo/pk9/2PBxRYeXQisrvtIbdmLeDvZIxfJlHHjwoZzNHIVO4UxZa6foqL2B6kV3MhSKfF9kAvmN7pggzw2k+Hs4=
  - secure: UzwvnIpff7pIbk7jzF9rMqLZaVs4QddzyocnuF2/Fyhp0PbPhqTf8al41mzWN+40Y+l1xX1indEnRoP2B28+oDAOV3+Qr8PCOwPC+4pxRo4oC1WW5VPhSFVhlROES/Ui5sOJK9gbpLPR6b1l3Aj91LX1ay8tI+a8wiWuzHpyyx69afnyFiMidYDPqw7OCW1bowvAnGOOI7Jm96NPLytEW3AqDt7Ea+eekkqSeZb1LBz2hxNeeRsMfdT4A3qf5uoJmWqK07GhA3aTOGS9ZYAIU/PUPHYeCPwjbpMfqso9DFeh1GqTzA2/HmSs2e0jzMPXneiPN3i8WkkuvF/FIVcyb7C16gXM6DmsuInLOyD+QpNQJ/I92TCYa84cf3ls373HwxIWPk3uVnItDLU3tv4Y/G3LlWyzJUtXQK4UwAzHdWoUXg5dQmYJ79PY7wT6xXmH3lUZWU86CKcFhb2NYIf9gieSI9fuTihB0CSJPJ+u4onglumVn99QZ1H5HHuMQQ4KuuZAmqn08jXECKSbRJujWaMe9wVXkBVbMUlEXRJVv8gUFgyhoLbA+Y1h4IAFzvUR5uaLU+pwc9iIMmFooPOmc6s33F+IOQ+cQNC9RYzwXNGBbpxjJVp8+5R1OOaaDJCHygsUNTlYfG+2s3GWQbMrOvhC47mT0Uw3kQzQvJk+N5E=
