sudo: false
language: java
cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/.m2"
jdk:
  - oraclejdk8

before_script:
  - echo 'Asia/Tokyo' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata

after_success:
  - mvn clean test jacoco:report coveralls:report

# deploy:
#   provider: script
#   script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -Dmaven.test.skip=true"
#   skip_cleanup: true
#   on:
#     branch: master

notifications:
  email:
    recipients:
      - gr-tig-oss@future.co.jp
    on_success: change # default: change
    on_failure: always # default: always
