/**
 * jp.co.future.uroborosql.parameter.ParameterTest
 */
SELECT
	*
FROM
	(
		SELECT
			CAST('2000-01-01'	AS	DATE)	AS	TARGET_DATE
		FROM
			SYSIBM.SYSDUMMY1
		UNION ALL
		SELECT
			CAST('2001-01-01'	AS	DATE)	AS	TARGET_DATE
		FROM
			SYSIBM.SYSDUMMY1
		UNION ALL
		SELECT
			CAST('2002-01-01'	AS	DATE)	AS	TARGET_DATE
		FROM
			SYSIBM.SYSDUMMY1
		UNION ALL
		SELECT
			CAST('2003-01-01'	AS	DATE)	AS	TARGET_DATE
		FROM
			SYSIBM.SYSDUMMY1
		UNION ALL
		SELECT
			CAST('2004-01-01'	AS	DATE)	AS	TARGET_DATE
		FROM
			SYSIBM.SYSDUMMY1
	)	TBL
WHERE
	TBL.TARGET_DATE	=	/*targetDate*/''