create table if not exists PRODUCT (
	PRODUCT_ID			INT NOT NULL,
	PRODUCT_NAME		VARCHAR(100),
	PRODUCT_KANA_NAME	VARCHAR(100),
	JAN_CODE			CHAR(13),
	PRODUCT_DESCRIPTION	VARCHAR(100),
	INS_DATETIME		DATETIME,
	UPD_DATETIME		DATETIME,
	VERSION_NO			INT,
	constraint PK_PRODUCT primary key (PRODUCT_ID)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
;

create table if not exists PRODUCT_REGIST_WORK (
	PRODUCT_NAME		VARCHAR(100),
	PRODUCT_KANA_NAME	VARCHAR(100),
	JAN_CODE			CHAR(13),
	PRODUCT_DESCRIPTION	VARCHAR(100),
	INS_DATETIME		DATETIME
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
;

create table if not exists COLUMN_TYPE_TEST (
	COL_VARCHAR			VARCHAR(100),
	COL_CHAR			CHAR(10),
	COL_NUMERIC			NUMERIC(5, 2),
	COL_BOOLEAN			BOOLEAN,
	COL_TIMESTAMP		DATETIME,
	COL_DATE			DATE,
	COL_TIME			TIME
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
;
