name: Publish package to the Maven Central Repository

on:
  release:
    types: [ published ]

jobs:
  publish-release:
    name: Release on Maven Central
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Tokyo

    steps:
      - uses: actions/checkout@v4

      - name: 🛠️ Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'adopt'
          cache: 'maven'
      
      - name: Build with Maven
        run: mvn --batch-mode --no-transfer-progress package

      - name: 🛠️ Set up Apache Maven Central
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'adopt'
          cache: 'maven'
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Publish Release Package
        run: mvn --batch-mode --no-transfer-progress --settings ./settings/.maven.settings.xml -DperformRelease=true -DskipTests=true clean deploy
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
