create table if not exists PRODUCT (
	PRODUCT_ID			NUMERIC(10, 0),
	PRODUCT_NAME		VARCHAR(100),
	PRODUCT_KANA_NAME	VARCHAR(100),
	JAN_CODE			CHAR(13),
	PRODUCT_DESCRIPTION	VARCHAR(100),
	INS_DATETIME		TIMESTAMP,
	UPD_DATETIME		TIMESTAMP,
	VERSION_NO			NUMERIC(10, 0),
	constraint PK_PRODUCT primary key (PRODUCT_ID)
)
;

create table if not exists PRODUCT_REGIST_WORK (
	PRODUCT_NAME		VARCHAR(100),
	PRODUCT_KANA_NAME	VARCHAR(100),
	JAN_CODE			CHAR(13),
	PRODUCT_DESCRIPTION	VARCHAR(100),
	INS_DATETIME		TIMESTAMP
)
;
