create table if not exists PRODUCT (
	PRODUCT_ID			NUMERIC(10, 0),
	PRODUCT_NAME		VARCHAR(100),
	PRODUCT_KANA_NAME	VARCHAR(100),
	JAN_CODE			CHAR(13),
	PRODUCT_DESCRIPTION	VARCHAR(100),
	INS_DATETIME		TIMESTAMP,
	UPD_DATETIME		TIMESTAMP,
	VERSION_NO			NUMERIC(10, 0),
	constraint PK_PRODUCT primary key (PRODUCT_ID)
)
;

create table if not exists PRODUCT_REGIST_WORK (
	PRODUCT_NAME		VARCHAR(100),
	PRODUCT_KANA_NAME	VARCHAR(100),
	JAN_CODE			CHAR(13),
	PRODUCT_DESCRIPTION	VARCHAR(100),
	INS_DATETIME		TIMESTAMP
)
;

create table if not exists COLUMN_TYPE_TEST (
	COL_VARCHAR			VARCHAR(100),
	COL_CHAR			CHAR(10),
	COL_NUMERIC			NUMERIC(4, 2),
	COL_BOOLEAN			BOOLEAN,
	COL_TIMESTAMP		TIMESTAMP,
	COL_DATE			DATE,
	COL_TIME			TIME
)
;
